//
//  MarkdownExporter.swift
//  easyshortcut
//
//  Service for exporting shortcuts to Markdown format
//

internal import Foundation
internal import AppKit

/// Service class that exports shortcuts to well-formatted Markdown
@MainActor
final class MarkdownExporter {
    static let shared = MarkdownExporter()
    
    private init() {}
    
    /// Exports shortcuts to a Markdown file and presents a save dialog
    /// - Parameters:
    ///   - shortcuts: Array of ShortcutItem to export
    ///   - appName: Name of the application these shortcuts belong to
    func exportToMarkdown(shortcuts: [ShortcutItem], appName: String) {
        let markdown = generateMarkdown(shortcuts: shortcuts, appName: appName)
        presentSaveDialog(content: markdown, appName: appName)
    }
    
    /// Generates well-formatted Markdown content from shortcuts
    /// - Parameters:
    ///   - shortcuts: Array of ShortcutItem to convert
    ///   - appName: Name of the application
    /// - Returns: Formatted Markdown string
    private func generateMarkdown(shortcuts: [ShortcutItem], appName: String) -> String {
        var markdown = ""
        
        // Title
        markdown += "# \(appName) - Keyboard Shortcuts\n\n"
        
        // Metadata
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .long
        dateFormatter.timeStyle = .short
        let dateString = dateFormatter.string(from: Date())
        
        markdown += "**Exported:** \(dateString)  \n"
        markdown += "**Total Shortcuts:** \(shortcuts.count)\n\n"
        
        markdown += "---\n\n"
        
        // Group shortcuts by top-level menu
        let groupedShortcuts = Dictionary(grouping: shortcuts) { shortcut -> String in
            shortcut.menuPath.first ?? "Other"
        }
        
        // Sort menu groups alphabetically
        let sortedGroups = groupedShortcuts.keys.sorted()
        
        for menuGroup in sortedGroups {
            guard let items = groupedShortcuts[menuGroup] else { continue }
            
            // Menu group heading
            markdown += "## \(menuGroup)\n\n"
            
            // Create table
            markdown += "| Command | Shortcut | Path |\n"
            markdown += "|---------|----------|------|\n"
            
            // Sort items by title
            let sortedItems = items.sorted { $0.title < $1.title }
            
            for item in sortedItems {
                let title = escapeMarkdown(item.title)
                let shortcut = item.shortcut ?? "-"
                let path = escapeMarkdown(item.fullPath)
                
                markdown += "| \(title) | `\(shortcut)` | \(path) |\n"
            }
            
            markdown += "\n"
        }
        
        // Footer
        markdown += "---\n\n"
        markdown += "*Generated by [easyshortcut](https://github.com/joaolucaswork/easyshortcut)*\n"
        
        return markdown
    }
    
    /// Escapes special Markdown characters in text
    /// - Parameter text: Text to escape
    /// - Returns: Escaped text safe for Markdown
    private func escapeMarkdown(_ text: String) -> String {
        return text
            .replacingOccurrences(of: "|", with: "\\|")
            .replacingOccurrences(of: "\n", with: " ")
    }
    
    /// Presents a save dialog to save the Markdown content
    /// - Parameters:
    ///   - content: Markdown content to save
    ///   - appName: Name of the app (used for default filename)
    private func presentSaveDialog(content: String, appName: String) {
        let savePanel = NSSavePanel()
        savePanel.allowedContentTypes = [.plainText]
        savePanel.canCreateDirectories = true
        savePanel.isExtensionHidden = false
        savePanel.title = "Export Shortcuts to Markdown"
        savePanel.message = "Choose a location to save the shortcuts"
        savePanel.nameFieldLabel = "File Name:"

        // Generate default filename
        let sanitizedAppName = appName
            .replacingOccurrences(of: " ", with: "_")
            .replacingOccurrences(of: "/", with: "_")
        savePanel.nameFieldStringValue = "\(sanitizedAppName)_shortcuts.md"

        // Make the panel appear in front of all windows
        savePanel.level = .modalPanel

        // Run modal to ensure it appears on top
        let response = savePanel.runModal()

        guard response == .OK, let url = savePanel.url else {
            return
        }

        do {
            try content.write(to: url, atomically: true, encoding: .utf8)
            NSLog("✅ MarkdownExporter: Successfully exported shortcuts to \(url.path)")

            // Show success notification
            self.showSuccessNotification(filename: url.lastPathComponent)
        } catch {
            NSLog("❌ MarkdownExporter: Failed to save file - \(error.localizedDescription)")
            self.showErrorAlert(error: error)
        }
    }
    
    /// Shows a success notification
    /// - Parameter filename: Name of the saved file
    private func showSuccessNotification(filename: String) {
        let alert = NSAlert()
        alert.messageText = "Export Successful"
        alert.informativeText = "Shortcuts exported to \(filename)"
        alert.alertStyle = .informational
        alert.addButton(withTitle: "OK")
        alert.runModal()
    }
    
    /// Shows an error alert
    /// - Parameter error: The error that occurred
    private func showErrorAlert(error: any Error) {
        let alert = NSAlert()
        alert.messageText = "Export Failed"
        alert.informativeText = error.localizedDescription
        alert.alertStyle = .critical
        alert.addButton(withTitle: "OK")
        alert.runModal()
    }
}

